name: Release
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: false
on:
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    release:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: fregante/setup-git-user@v2
            - uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: 17
            - uses: actions/cache@v3
              with:
                  path: |
                      buildSrc/.gradle
                      buildSrc/build
                  key: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle', 'buildSrc/src/**') }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle-${{ hashFiles('buildSrc/build.gradle', 'buildSrc/src/**') }}
            - uses: gradle/gradle-build-action@v2
              with:
                  arguments: build javadoc
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
            - uses: actions/configure-pages@v3
            - uses: actions/upload-pages-artifact@v2
              with:
                  path: 'build/docs/javadoc'
            - id: deployment
              uses: actions/deploy-pages@v2
            - uses: gradle/gradle-build-action@v2
              with:
                  arguments: publish
                  cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
              env:
                  MAVEN_PASSWORD: ${{ secrets.RELEASE_MAVEN_PASSWORD }}
                  MAVEN_USER: github
                  MAVEN_URL: https://maven.lukebemish.dev/releases/
