name: Release
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: false
on:
    workflow_dispatch:
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    release:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: fregante/setup-git-user@v2
            - uses: actions/setup-java@v5
              with:
                  distribution: "temurin"
                  java-version: 21
            - uses: gradle/actions/setup-gradle@v5
            - name: Build
              run: ./gradlew build javadoc
            - uses: actions/configure-pages@v3
            - uses: actions/upload-pages-artifact@v4
              with:
                  path: 'build/docs/javadoc'
            - id: deployment
              uses: actions/deploy-pages@v4
            - name: Publish
              run: ./gradlew publish
              env:
                  MAVEN_PASSWORD: ${{ secrets.RELEASE_MAVEN_PASSWORD }}
                  MAVEN_USER: github
                  MAVEN_URL: https://maven.lukebemish.dev/releases/
